### ISSUE TITLE
Loading status functionality

### ISSUE THREAD

**Issue by songz** [songz/Facebook-Album#5]
Need a way to show the loading status of pictures.

**Comment by FongChin** [comment]
My thought on how to solve this:
1) After users drop the file on the website, I will show an overlay backdrop and show progress bar (status of how much of each picture is uploaded in real time.
2) After finish uploading, the user can just click on close button to go back to the home page.

**Comment by evaz** [comment]
can users upload different pics to several albums at once?
When you say backdrop, does that mean the user will see nothing but the
progress bar?

On Wed, Aug 1, 2012 at 11:07 PM, FongChin <
reply@reply.github.com

**Comment by FongChin** [comment]
Users can only upload pictures to the same album at once. And yes, users will only see the progress bar. It will be like login overlay.

**Comment by songz** [comment]
Done! Files are uploaded and when it's done it will automatically close.
